### ISSUE TITLE
날짜 정보가 틀리게 표시되고 있는거 같아요

### ISSUE THREAD

**Issue by smartbos** [ModernPUG/allblog#16]
![2015-06-15 15 31 52](https://cloud.githubusercontent.com/assets/6157033/8154302/ba7dff64-1373-11e5-8e23-f6d106a702a7.png)

이 글은 어제(6월 14일) 작성한 글인데 6월 2일 작성되었다고 나오고 있어서 뭔가 점검이 필요할 것 같습니다~

**Comment by smartbos** [comment]
#8 이슈와 함께 해결하면 될 듯 합니다.

**Comment by koojunho** [comment]
@smartbos  https://github.com/ModernPUG/allblog/commit/fc928c32a71241456f27bfd5a10d5f9e0d83ab2b timezone 지정했습니다. master branch 아니고 설정해주신 그대로 넣었습니다. 잘 합치셔서 운영서버에서 확인 부탁드리겠습니다. 제 서버에서는 현재 날짜로는 잘 나오네요. 그런데 그전에 궁금한 점이 크롤링된 날짜가 나오는 게 맞나요, 아니면 글이 작성된 날짜가 나오는 게 맞나요? 후자일듯 한데 다 같은 날짜가 나옵니다. 첨부 이미지는 제 서버에서의 스크린샷.

![image](https://cloud.githubusercontent.com/assets/334933/8157753/253486de-1392-11e5-94ca-7d44b08bfa6f.png)

**Comment by smartbos** [comment]
@koojunho 현재는 크롤링된 날짜 정보가 나오고 있는데 글이 작성된 날짜로 바꾸는게 맞는것 같아요. #8 이슈가 그 내용입니다. :)
